//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPolice.VPServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DenunciaWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class DenunciaWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_DenuncianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_expedienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualPolice.VPServiceReference.DesaparicionWS DesaparicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_hechoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direccion_hechoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_hechoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan Hora_hechoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Naturaleza_lugar_hechoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumPlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualPolice.VPServiceReference.RoboCocheWS RoboCocheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualPolice.VPServiceReference.SecuestroWS SecuestroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_Denunciante {
            get {
                return this.DNI_DenuncianteField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_DenuncianteField, value) != true)) {
                    this.DNI_DenuncianteField = value;
                    this.RaisePropertyChanged("DNI_Denunciante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_expediente {
            get {
                return this.DNI_expedienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_expedienteField, value) != true)) {
                    this.DNI_expedienteField = value;
                    this.RaisePropertyChanged("DNI_expediente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualPolice.VPServiceReference.DesaparicionWS Desaparicion {
            get {
                return this.DesaparicionField;
            }
            set {
                if ((object.ReferenceEquals(this.DesaparicionField, value) != true)) {
                    this.DesaparicionField = value;
                    this.RaisePropertyChanged("Desaparicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_hecho {
            get {
                return this.Descripcion_hechoField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_hechoField, value) != true)) {
                    this.Descripcion_hechoField = value;
                    this.RaisePropertyChanged("Descripcion_hecho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion_hecho {
            get {
                return this.Direccion_hechoField;
            }
            set {
                if ((object.ReferenceEquals(this.Direccion_hechoField, value) != true)) {
                    this.Direccion_hechoField = value;
                    this.RaisePropertyChanged("Direccion_hecho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_creacion {
            get {
                return this.Fecha_creacionField;
            }
            set {
                if ((this.Fecha_creacionField.Equals(value) != true)) {
                    this.Fecha_creacionField = value;
                    this.RaisePropertyChanged("Fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_hecho {
            get {
                return this.Fecha_hechoField;
            }
            set {
                if ((this.Fecha_hechoField.Equals(value) != true)) {
                    this.Fecha_hechoField = value;
                    this.RaisePropertyChanged("Fecha_hecho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Hora_hecho {
            get {
                return this.Hora_hechoField;
            }
            set {
                if ((this.Hora_hechoField.Equals(value) != true)) {
                    this.Hora_hechoField = value;
                    this.RaisePropertyChanged("Hora_hecho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naturaleza_lugar_hecho {
            get {
                return this.Naturaleza_lugar_hechoField;
            }
            set {
                if ((object.ReferenceEquals(this.Naturaleza_lugar_hechoField, value) != true)) {
                    this.Naturaleza_lugar_hechoField = value;
                    this.RaisePropertyChanged("Naturaleza_lugar_hecho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPlaca {
            get {
                return this.NumPlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumPlacaField, value) != true)) {
                    this.NumPlacaField = value;
                    this.RaisePropertyChanged("NumPlaca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualPolice.VPServiceReference.RoboCocheWS RoboCoche {
            get {
                return this.RoboCocheField;
            }
            set {
                if ((object.ReferenceEquals(this.RoboCocheField, value) != true)) {
                    this.RoboCocheField = value;
                    this.RaisePropertyChanged("RoboCoche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualPolice.VPServiceReference.SecuestroWS Secuestro {
            get {
                return this.SecuestroField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuestroField, value) != true)) {
                    this.SecuestroField = value;
                    this.RaisePropertyChanged("Secuestro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DesaparicionWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class DesaparicionWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_DesaparecidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_fisicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualPolice.VPServiceReference.FotoWS FotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_Desaparecido {
            get {
                return this.DNI_DesaparecidoField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_DesaparecidoField, value) != true)) {
                    this.DNI_DesaparecidoField = value;
                    this.RaisePropertyChanged("DNI_Desaparecido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_fisica {
            get {
                return this.Descripcion_fisicaField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_fisicaField, value) != true)) {
                    this.Descripcion_fisicaField = value;
                    this.RaisePropertyChanged("Descripcion_fisica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualPolice.VPServiceReference.FotoWS Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoboCocheWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class RoboCocheWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumBastidorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumBastidor {
            get {
                return this.NumBastidorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumBastidorField, value) != true)) {
                    this.NumBastidorField = value;
                    this.RaisePropertyChanged("NumBastidor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecuestroWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class SecuestroWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_CiudadanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_Ciudadano {
            get {
                return this.DNI_CiudadanoField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_CiudadanoField, value) != true)) {
                    this.DNI_CiudadanoField = value;
                    this.RaisePropertyChanged("DNI_Ciudadano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FotoWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class FotoWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Foto {
            get {
                return this.Id_FotoField;
            }
            set {
                if ((this.Id_FotoField.Equals(value) != true)) {
                    this.Id_FotoField = value;
                    this.RaisePropertyChanged("Id_Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgenteWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class AgenteWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Estado_CivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumPlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado_Civil {
            get {
                return this.Estado_CivilField;
            }
            set {
                if ((object.ReferenceEquals(this.Estado_CivilField, value) != true)) {
                    this.Estado_CivilField = value;
                    this.RaisePropertyChanged("Estado_Civil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPlaca {
            get {
                return this.NumPlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumPlacaField, value) != true)) {
                    this.NumPlacaField = value;
                    this.RaisePropertyChanged("NumPlaca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rango {
            get {
                return this.RangoField;
            }
            set {
                if ((object.ReferenceEquals(this.RangoField, value) != true)) {
                    this.RangoField = value;
                    this.RaisePropertyChanged("Rango");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadanoWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CiudadanoWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_NacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Huella_DactilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Letra_PisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CP {
            get {
                return this.CPField;
            }
            set {
                if ((object.ReferenceEquals(this.CPField, value) != true)) {
                    this.CPField = value;
                    this.RaisePropertyChanged("CP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Nacimiento {
            get {
                return this.Fecha_NacimientoField;
            }
            set {
                if ((this.Fecha_NacimientoField.Equals(value) != true)) {
                    this.Fecha_NacimientoField = value;
                    this.RaisePropertyChanged("Fecha_Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Huella_Dactilar {
            get {
                return this.Huella_DactilarField;
            }
            set {
                if ((object.ReferenceEquals(this.Huella_DactilarField, value) != true)) {
                    this.Huella_DactilarField = value;
                    this.RaisePropertyChanged("Huella_Dactilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Letra_Piso {
            get {
                return this.Letra_PisoField;
            }
            set {
                if ((object.ReferenceEquals(this.Letra_PisoField, value) != true)) {
                    this.Letra_PisoField = value;
                    this.RaisePropertyChanged("Letra_Piso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nacionalidad {
            get {
                return this.NacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadField, value) != true)) {
                    this.NacionalidadField = value;
                    this.RaisePropertyChanged("Nacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActividadWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ActividadWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan Hora_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan Hora_InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Hora_Fin {
            get {
                return this.Hora_FinField;
            }
            set {
                if ((this.Hora_FinField.Equals(value) != true)) {
                    this.Hora_FinField = value;
                    this.RaisePropertyChanged("Hora_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Hora_Inicio {
            get {
                return this.Hora_InicioField;
            }
            set {
                if ((this.Hora_InicioField.Equals(value) != true)) {
                    this.Hora_InicioField = value;
                    this.RaisePropertyChanged("Hora_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpedienteWS", Namespace="http://schemas.datacontract.org/2004/07/VPServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ExpedienteWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AlturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Estado_CivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_CreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_UltimaModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualPolice.VPServiceReference.FotoWS FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Altura {
            get {
                return this.AlturaField;
            }
            set {
                if ((this.AlturaField.Equals(value) != true)) {
                    this.AlturaField = value;
                    this.RaisePropertyChanged("Altura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado_Civil {
            get {
                return this.Estado_CivilField;
            }
            set {
                if ((object.ReferenceEquals(this.Estado_CivilField, value) != true)) {
                    this.Estado_CivilField = value;
                    this.RaisePropertyChanged("Estado_Civil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Creacion {
            get {
                return this.Fecha_CreacionField;
            }
            set {
                if ((this.Fecha_CreacionField.Equals(value) != true)) {
                    this.Fecha_CreacionField = value;
                    this.RaisePropertyChanged("Fecha_Creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_UltimaModif {
            get {
                return this.Fecha_UltimaModifField;
            }
            set {
                if ((this.Fecha_UltimaModifField.Equals(value) != true)) {
                    this.Fecha_UltimaModifField = value;
                    this.RaisePropertyChanged("Fecha_UltimaModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualPolice.VPServiceReference.FotoWS Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VPServiceReference.IVPService")]
    public interface IVPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AddDenuncia", ReplyAction="http://tempuri.org/IVPService/AddDenunciaResponse")]
        int AddDenuncia(VirtualPolice.VPServiceReference.DenunciaWS newDenuncia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AddDenuncia", ReplyAction="http://tempuri.org/IVPService/AddDenunciaResponse")]
        System.Threading.Tasks.Task<int> AddDenunciaAsync(VirtualPolice.VPServiceReference.DenunciaWS newDenuncia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/DeleteDenuncia", ReplyAction="http://tempuri.org/IVPService/DeleteDenunciaResponse")]
        bool DeleteDenuncia(int idDenuncia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/DeleteDenuncia", ReplyAction="http://tempuri.org/IVPService/DeleteDenunciaResponse")]
        System.Threading.Tasks.Task<bool> DeleteDenunciaAsync(int idDenuncia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetDenuncia", ReplyAction="http://tempuri.org/IVPService/GetDenunciaResponse")]
        VirtualPolice.VPServiceReference.DenunciaWS GetDenuncia(int idDenuncia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetDenuncia", ReplyAction="http://tempuri.org/IVPService/GetDenunciaResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.DenunciaWS> GetDenunciaAsync(int idDenuncia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetNotificaciones", ReplyAction="http://tempuri.org/IVPService/GetNotificacionesResponse")]
        VirtualPolice.VPServiceReference.DenunciaWS[] GetNotificaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetNotificaciones", ReplyAction="http://tempuri.org/IVPService/GetNotificacionesResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.DenunciaWS[]> GetNotificacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AddAgente", ReplyAction="http://tempuri.org/IVPService/AddAgenteResponse")]
        bool AddAgente(VirtualPolice.VPServiceReference.AgenteWS newAgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AddAgente", ReplyAction="http://tempuri.org/IVPService/AddAgenteResponse")]
        System.Threading.Tasks.Task<bool> AddAgenteAsync(VirtualPolice.VPServiceReference.AgenteWS newAgente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AddCiudadano", ReplyAction="http://tempuri.org/IVPService/AddCiudadanoResponse")]
        bool AddCiudadano(VirtualPolice.VPServiceReference.CiudadanoWS newCiudadano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AddCiudadano", ReplyAction="http://tempuri.org/IVPService/AddCiudadanoResponse")]
        System.Threading.Tasks.Task<bool> AddCiudadanoAsync(VirtualPolice.VPServiceReference.CiudadanoWS newCiudadano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetAgente", ReplyAction="http://tempuri.org/IVPService/GetAgenteResponse")]
        VirtualPolice.VPServiceReference.AgenteWS GetAgente(string numPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetAgente", ReplyAction="http://tempuri.org/IVPService/GetAgenteResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.AgenteWS> GetAgenteAsync(string numPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/ComprobarPassword", ReplyAction="http://tempuri.org/IVPService/ComprobarPasswordResponse")]
        bool ComprobarPassword(string numPlaca, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/ComprobarPassword", ReplyAction="http://tempuri.org/IVPService/ComprobarPasswordResponse")]
        System.Threading.Tasks.Task<bool> ComprobarPasswordAsync(string numPlaca, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetCiudadano", ReplyAction="http://tempuri.org/IVPService/GetCiudadanoResponse")]
        VirtualPolice.VPServiceReference.CiudadanoWS GetCiudadano(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetCiudadano", ReplyAction="http://tempuri.org/IVPService/GetCiudadanoResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.CiudadanoWS> GetCiudadanoAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetAgentes", ReplyAction="http://tempuri.org/IVPService/GetAgentesResponse")]
        VirtualPolice.VPServiceReference.AgenteWS[] GetAgentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetAgentes", ReplyAction="http://tempuri.org/IVPService/GetAgentesResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.AgenteWS[]> GetAgentesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetPlanning", ReplyAction="http://tempuri.org/IVPService/GetPlanningResponse")]
        VirtualPolice.VPServiceReference.ActividadWS[] GetPlanning(string numPlaca, System.DateTime fecha, int dias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetPlanning", ReplyAction="http://tempuri.org/IVPService/GetPlanningResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.ActividadWS[]> GetPlanningAsync(string numPlaca, System.DateTime fecha, int dias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/ComprobarCiuAgente", ReplyAction="http://tempuri.org/IVPService/ComprobarCiuAgenteResponse")]
        bool ComprobarCiuAgente(string numPlaca, string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/ComprobarCiuAgente", ReplyAction="http://tempuri.org/IVPService/ComprobarCiuAgenteResponse")]
        System.Threading.Tasks.Task<bool> ComprobarCiuAgenteAsync(string numPlaca, string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/ComprobarConexion", ReplyAction="http://tempuri.org/IVPService/ComprobarConexionResponse")]
        bool ComprobarConexion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/ComprobarConexion", ReplyAction="http://tempuri.org/IVPService/ComprobarConexionResponse")]
        System.Threading.Tasks.Task<bool> ComprobarConexionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetExpediente", ReplyAction="http://tempuri.org/IVPService/GetExpedienteResponse")]
        VirtualPolice.VPServiceReference.ExpedienteWS GetExpediente(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetExpediente", ReplyAction="http://tempuri.org/IVPService/GetExpedienteResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.ExpedienteWS> GetExpedienteAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/CrearExpediente", ReplyAction="http://tempuri.org/IVPService/CrearExpedienteResponse")]
        bool CrearExpediente(VirtualPolice.VPServiceReference.ExpedienteWS expediente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/CrearExpediente", ReplyAction="http://tempuri.org/IVPService/CrearExpedienteResponse")]
        System.Threading.Tasks.Task<bool> CrearExpedienteAsync(VirtualPolice.VPServiceReference.ExpedienteWS expediente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AsociarExpediente", ReplyAction="http://tempuri.org/IVPService/AsociarExpedienteResponse")]
        bool AsociarExpediente(int id_denuncia, string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/AsociarExpediente", ReplyAction="http://tempuri.org/IVPService/AsociarExpedienteResponse")]
        System.Threading.Tasks.Task<bool> AsociarExpedienteAsync(int id_denuncia, string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetDenuncias", ReplyAction="http://tempuri.org/IVPService/GetDenunciasResponse")]
        VirtualPolice.VPServiceReference.DenunciaWS[] GetDenuncias(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVPService/GetDenuncias", ReplyAction="http://tempuri.org/IVPService/GetDenunciasResponse")]
        System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.DenunciaWS[]> GetDenunciasAsync(string DNI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVPServiceChannel : VirtualPolice.VPServiceReference.IVPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VPServiceClient : System.ServiceModel.ClientBase<VirtualPolice.VPServiceReference.IVPService>, VirtualPolice.VPServiceReference.IVPService {
        
        public VPServiceClient() {
        }
        
        public VPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddDenuncia(VirtualPolice.VPServiceReference.DenunciaWS newDenuncia) {
            return base.Channel.AddDenuncia(newDenuncia);
        }
        
        public System.Threading.Tasks.Task<int> AddDenunciaAsync(VirtualPolice.VPServiceReference.DenunciaWS newDenuncia) {
            return base.Channel.AddDenunciaAsync(newDenuncia);
        }
        
        public bool DeleteDenuncia(int idDenuncia) {
            return base.Channel.DeleteDenuncia(idDenuncia);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDenunciaAsync(int idDenuncia) {
            return base.Channel.DeleteDenunciaAsync(idDenuncia);
        }
        
        public VirtualPolice.VPServiceReference.DenunciaWS GetDenuncia(int idDenuncia) {
            return base.Channel.GetDenuncia(idDenuncia);
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.DenunciaWS> GetDenunciaAsync(int idDenuncia) {
            return base.Channel.GetDenunciaAsync(idDenuncia);
        }
        
        public VirtualPolice.VPServiceReference.DenunciaWS[] GetNotificaciones() {
            return base.Channel.GetNotificaciones();
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.DenunciaWS[]> GetNotificacionesAsync() {
            return base.Channel.GetNotificacionesAsync();
        }
        
        public bool AddAgente(VirtualPolice.VPServiceReference.AgenteWS newAgente) {
            return base.Channel.AddAgente(newAgente);
        }
        
        public System.Threading.Tasks.Task<bool> AddAgenteAsync(VirtualPolice.VPServiceReference.AgenteWS newAgente) {
            return base.Channel.AddAgenteAsync(newAgente);
        }
        
        public bool AddCiudadano(VirtualPolice.VPServiceReference.CiudadanoWS newCiudadano) {
            return base.Channel.AddCiudadano(newCiudadano);
        }
        
        public System.Threading.Tasks.Task<bool> AddCiudadanoAsync(VirtualPolice.VPServiceReference.CiudadanoWS newCiudadano) {
            return base.Channel.AddCiudadanoAsync(newCiudadano);
        }
        
        public VirtualPolice.VPServiceReference.AgenteWS GetAgente(string numPlaca) {
            return base.Channel.GetAgente(numPlaca);
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.AgenteWS> GetAgenteAsync(string numPlaca) {
            return base.Channel.GetAgenteAsync(numPlaca);
        }
        
        public bool ComprobarPassword(string numPlaca, string pass) {
            return base.Channel.ComprobarPassword(numPlaca, pass);
        }
        
        public System.Threading.Tasks.Task<bool> ComprobarPasswordAsync(string numPlaca, string pass) {
            return base.Channel.ComprobarPasswordAsync(numPlaca, pass);
        }
        
        public VirtualPolice.VPServiceReference.CiudadanoWS GetCiudadano(string dni) {
            return base.Channel.GetCiudadano(dni);
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.CiudadanoWS> GetCiudadanoAsync(string dni) {
            return base.Channel.GetCiudadanoAsync(dni);
        }
        
        public VirtualPolice.VPServiceReference.AgenteWS[] GetAgentes() {
            return base.Channel.GetAgentes();
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.AgenteWS[]> GetAgentesAsync() {
            return base.Channel.GetAgentesAsync();
        }
        
        public VirtualPolice.VPServiceReference.ActividadWS[] GetPlanning(string numPlaca, System.DateTime fecha, int dias) {
            return base.Channel.GetPlanning(numPlaca, fecha, dias);
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.ActividadWS[]> GetPlanningAsync(string numPlaca, System.DateTime fecha, int dias) {
            return base.Channel.GetPlanningAsync(numPlaca, fecha, dias);
        }
        
        public bool ComprobarCiuAgente(string numPlaca, string DNI) {
            return base.Channel.ComprobarCiuAgente(numPlaca, DNI);
        }
        
        public System.Threading.Tasks.Task<bool> ComprobarCiuAgenteAsync(string numPlaca, string DNI) {
            return base.Channel.ComprobarCiuAgenteAsync(numPlaca, DNI);
        }
        
        public bool ComprobarConexion() {
            return base.Channel.ComprobarConexion();
        }
        
        public System.Threading.Tasks.Task<bool> ComprobarConexionAsync() {
            return base.Channel.ComprobarConexionAsync();
        }
        
        public VirtualPolice.VPServiceReference.ExpedienteWS GetExpediente(string DNI) {
            return base.Channel.GetExpediente(DNI);
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.ExpedienteWS> GetExpedienteAsync(string DNI) {
            return base.Channel.GetExpedienteAsync(DNI);
        }
        
        public bool CrearExpediente(VirtualPolice.VPServiceReference.ExpedienteWS expediente) {
            return base.Channel.CrearExpediente(expediente);
        }
        
        public System.Threading.Tasks.Task<bool> CrearExpedienteAsync(VirtualPolice.VPServiceReference.ExpedienteWS expediente) {
            return base.Channel.CrearExpedienteAsync(expediente);
        }
        
        public bool AsociarExpediente(int id_denuncia, string DNI) {
            return base.Channel.AsociarExpediente(id_denuncia, DNI);
        }
        
        public System.Threading.Tasks.Task<bool> AsociarExpedienteAsync(int id_denuncia, string DNI) {
            return base.Channel.AsociarExpedienteAsync(id_denuncia, DNI);
        }
        
        public VirtualPolice.VPServiceReference.DenunciaWS[] GetDenuncias(string DNI) {
            return base.Channel.GetDenuncias(DNI);
        }
        
        public System.Threading.Tasks.Task<VirtualPolice.VPServiceReference.DenunciaWS[]> GetDenunciasAsync(string DNI) {
            return base.Channel.GetDenunciasAsync(DNI);
        }
    }
}
