//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int ID_Actividad { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora_Inicio { get; set; }
        public System.TimeSpan Hora_Fin { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public int AgenteID_Agente { get; set; }
    
        public virtual Agente Agente { get; set; }
    }
}
