//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public Expediente()
        {
            this.Denuncia = new HashSet<Denuncia>();
        }
    
        public int ID_Expediente { get; set; }
        public Nullable<double> Altura { get; set; }
        public Nullable<double> Peso { get; set; }
        public int Edad { get; set; }
        public string Estado_Civil { get; set; }
        public string Telefono { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public System.DateTime Fecha_UltimaModif { get; set; }
    
        public virtual ICollection<Denuncia> Denuncia { get; set; }
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual Foto Foto { get; set; }
    }
}
