//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.RoboCoche = new HashSet<RoboCoche>();
        }
    
        public int ID_Vehiculo { get; set; }
        public string Matricula { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public string NumBastidor { get; set; }
        public int CiudadanoID_Ciudadano { get; set; }
    
        public virtual ICollection<RoboCoche> RoboCoche { get; set; }
        public virtual Ciudadano Ciudadano { get; set; }
    }
}
